recipe-graphics/waffle: Add depends on cmake-native
Fixes,

  ...
    File "/home/builds/oe-rpb-master/build-410c/tmp-rpb-glibc/work/cortexa53-linaro-linux/waffle/1.7.0-r0/recipe-sysroot-native/usr/lib/python3.10/site-packages/mesonbuild/modules/cmake.py", line 241, in detect_cmake
      p, stdout, stderr = mesonlib.Popen_safe(cmakebin.get_command() + ['--system-information', '-G', 'Ninja'])[0:3]
    File "/home/builds/oe-rpb-master/build-410c/tmp-rpb-glibc/work/cortexa53-linaro-linux/waffle/1.7.0-r0/recipe-sysroot-native/usr/lib/python3.10/site-packages/mesonbuild/mesonlib/universal.py", line 1397, in Popen_safe
      p = subprocess.Popen(args, universal_newlines=True, close_fds=False,
    File "/home/builds/oe-rpb-master/build-410c/tmp-rpb-glibc/work/cortexa53-linaro-linux/waffle/1.7.0-r0/recipe-sysroot-native/usr/lib/python3.10/subprocess.py", line 966, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/home/builds/oe-rpb-master/build-410c/tmp-rpb-glibc/work/cortexa53-linaro-linux/waffle/1.7.0-r0/recipe-sysroot-native/usr/lib/python3.10/subprocess.py", line 1717, in _execute_child
      and os.path.dirname(executable)
    File "/home/builds/oe-rpb-master/build-410c/tmp-rpb-glibc/work/cortexa53-linaro-linux/waffle/1.7.0-r0/recipe-sysroot-native/usr/lib/python3.10/posixpath.py", line 152, in dirname
      p = os.fspath(p)
  ...

Not inherit cmake class because expects meson-log.txt,

  ...

  File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
       0001:
   *** 0002:meson_do_qa_configure(d)
       0003:
  File: '/home/builds/oe-rpb-master/build-410c/conf/../../layers/openembedded-core/meta/classes/meson.bbclass', lineno: 130, function: meson_do_qa_configure
       0126:
       0127:python meson_do_qa_configure() {
       0128:    import re
       0129:    warn_re = re.compile(r"^WARNING: Cross property (.+) is using default value (.+)$", re.MULTILINE)
   *** 0130:    with open(d.expand("${B}/meson-logs/meson-log.txt")) as logfile:
       0131:        log = logfile.read()
       0132:    for (prop, value) in warn_re.findall(log):
       0133:        bb.warn("Meson cross property %s used without explicit assignment, defaulting to %s" % (prop, value))
       0134:}
  Exception: FileNotFoundError: [Errno 2] No such file or directory: '/home/builds/oe-rpb-master/build-410c/tmp-rpb-glibc/work/cortexa53-linaro-linux/waffle/1.7.0-r0/build/meson-logs/meson-log.txt'
  ...

Signed-off-by: Aníbal Limón <anibal.limon@linaro.org>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>